### ISSUE TITLE
Deprecation notice for roughtime.cloudflare.com:2002

### ISSUE THREAD

**Issue by cjpatton** [oreparaz/vroughtime#16]
The Cloudflare Roughtime server at roughtime.cloudflare.com:2002 has been deprecated and will be turned off on July 1, 2024. You may wish to update your client to use our new server to avoid a disruption of service:

```
{
    "name": "Cloudflare-Roughtime-2",
    "publicKeyType": "ed25519",
    "publicKey": "0GD7c3yP8xEc4Zl2zeuN2SlLvDVVocjsPSL8/Rl/7zg=",
    "addresses": [
        {
            "protocol": "udp",
            "address": "roughtime.cloudflare.com:2003"
        }
    ]
}
```

See https://groups.google.com/a/chromium.org/g/proto-roughtime/c/vbmjoudG184 for further details.

**Comment by oreparaz** [comment]
Thanks for the note, @cjpatton! I see this in the NTP post:

> Our server currently implements draft 08. We will soon move to draft 09
> without backwards compatibility for 08, unless we see a significant number
> of clients using draft 08. We will continue to support Google Roughtime,
> since we do see a significant amount of traffic for that version. You can
> use the public key above with either IETF or Google-Roughtime.
>
> Note that this server is intended to support interop testing by the
> community and is not guaranteed to stay up long-term.

This probably means I'll just update the config to point to the new server, as `Cloudflare-Roughtime-2` will still talk pre-IETF roughtime.
